[tool.poetry]
name = "rseadmin"
version = "0.1.0"
description = "RSE Admin Resource Allocation and Finance tool"
authors = ["Paul Richmond <p.richmond@sheffield.ac.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6"
Django = "~2.2"
django-adminlte2 = "~0.4.1"
django-polymorphic = "~2.1"
gunicorn = {version = "^19.9", optional = true}
psycopg2 = {version = "^2.8", optional = true}
mysqlclient = {version = "~1.4.4", optional = true}

[tool.poetry.dev-dependencies]
pytest-cov = "^2.7"
codecov = "^2.0"
pytest = "^4.5"
sphinx = "^2.2"
sphinx_rtd_theme = "^0.4.3"
selenium = "^3.141"

[tool.poetry.extras]
pgsql = ["psycopg2"]
gunicorn = ["gunicorn"]
mysql = ["mysqlclient"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
