# Generated by Django 3.2.25 on 2024-05-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0003_alter_timesheetentry_id'),
        ('rse', '0008_alter_directlyincurredproject_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryband',
            name='year',
        ),
        migrations.RemoveField(
            model_name='salarygradechange',
            name='rse',
        ),
        migrations.RemoveField(
            model_name='salarygradechange',
            name='salary_band',
        ),
        migrations.RemoveField(
            model_name='serviceproject',
            name='project_ptr',
        ),
        migrations.RemoveField(
            model_name='directlyincurredproject',
            name='overheads',
        ),
        migrations.RemoveField(
            model_name='directlyincurredproject',
            name='salary_band',
        ),
        migrations.DeleteModel(
            name='FinancialYear',
        ),
        migrations.DeleteModel(
            name='SalaryBand',
        ),
        migrations.DeleteModel(
            name='SalaryGradeChange',
        ),
        migrations.DeleteModel(
            name='ServiceProject',
        ),
    ]
