# Generated by Django 3.2.25 on 2024-05-13 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0009_auto_20240513_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='rse',
            name='employed_from',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 0, 0)),
        ),
    ]
