# Generated by Django 3.2.25 on 2024-05-13 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0010_rse_employed_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rse',
            name='employed_until',
            field=models.DateField(default=datetime.datetime(2099, 1, 1, 0, 0)),
        ),
    ]
